apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanakkam-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanakkam-world
  template:
    metadata:
      labels:
        app: vanakkam-world
    spec:
      containers:
        - name: vanakkam-world
          image: pradeepf5/vanakkam-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vanakkam-world-service
spec:
  selector:
    app: vanakkam-world
  ports:
    - protocol: TCP
      port: 84  
      targetPort: 8080  
  type: LoadBalancer 
